feat: update node graph
eve-autonomy/proj_launch pull request #15
Opened 2023-07-04 07:27 UTC by sfukuta

# Description
Add the description about the cargo loading function because it is not in the node graph.

2023-08-21 02:07 UTC, yn-mrse requested changes

2023-08-21 02:07 UTC, yn-mrse commented on README.md
> +      - [/button_output_selector](https://github.com/eve-autonomy/button_output_selector)
これは意図しない変更ではないでしょうか？
```suggestion
      - [/button_output_selector](https://github.com/eve-autonomy/button_output_selector)
```

2023-08-21 02:07 UTC, yn-mrse commented on docs/node_graph.pu
> +
rectangleのスコープの命名ルールは統一いただけますでしょうか？
module/service/functionと統一感がないです。

2023-08-21 02:12 UTC, yn-mrse requested changes
![image](https://github.com/eve-autonomy/proj_launch/assets/33311630/c0507123-c9d6-4612-b0b4-f16cf60c6559)
ondemand delivery functionとautoware_state_machine間の矢印がv2i control functionを横断してしまっており読みにくいです。

ondemand delivery functionの塊をautoware_state_machineの左へ移動いただけますでしょうか？

2023-08-21 02:14 UTC, yn-mrse commented
現時点のautoware_state_machineはengage serviceに含まれる理解ですが、図では異なるように見えます。
あわせたほうがいいのではないでしょうか？

2023-08-21 05:00 UTC, sfukuta commented on docs/node_graph.pu
> +
https://github.com/eve-autonomy/proj_launch/pull/15/commits/34806ebbb3c825a953d39a71abf9dbdf1da2a4a2
にて対応しました。

2023-08-25 02:22 UTC, yn-mrse commented
> ondemand delivery functionとautoware_state_machine間の矢印がv2i control functionを横断してしまっており読みにくいです。
ondemand delivery functionの塊をautoware_state_machineの左へ移動いただけますでしょうか？

> 現時点のautoware_state_machineはengage serviceに含まれる理解ですが、図では異なるように見えます。
あわせたほうがいいのではないでしょうか？


最新コミット https://github.com/eve-autonomy/proj_launch/pull/15/commits/a2046a79e7a5311af84d951f8850eda423b07ba3 時点で上記2点の修正が完了していることを確認しました。

![image](https://github.com/eve-autonomy/proj_launch/assets/33311630/7f5e7c57-efb8-4ca3-8c0e-ed4e5c488111)

2023-08-25 02:27 UTC, yn-mrse commented
@sfukuta 
README.mdについて、今回新たにengage moduleやinparking moduleが追加になっているはずですがそのあたりのリポジトリリンクの追記が漏れていませんか？

基本的にこのProj launchで起動するノードの依存関係としてのリポジトリのリストを網羅的に記載する必要があります。

2023-08-28 09:38 UTC, sfukuta commented
@yn-mrse 
> README.mdについて、今回新たにengage moduleやinparking moduleが追加になっているはずですがそのあたりのリポジトリリンクの追記が漏れていませんか？

https://github.com/eve-autonomy/proj_launch/pull/15/commits/65a16b8b91aac3161d7a16a089a3d2787f0b95f6 にて対応完了しました。

2023-09-01 05:30 UTC, yn-mrse requested changes

2023-09-01 05:30 UTC, yn-mrse commented on README.md
> +<details><summary>List of 参照 repositories</summary><div>
```suggestion
<details><summary>List of reference repositories</summary><div>
```
なぜかここだけ日本語が混じってるので違和感があります。

2023-09-01 05:30 UTC, yn-mrse commented on README.md
> +  - Base:
```suggestion
  - Message type used within other message:
```
説明が少なすぎてよくわからないです。

2023-09-01 05:35 UTC, yn-mrse requested changes
トピック名同士・矢印同士のオーバーラップや
トピック名と矢印のオーバーラップがあり、
見にくいので修正をお願いします。

![image](https://github.com/eve-autonomy/proj_launch/assets/33311630/96beab20-af54-40d8-a3e6-ca714ad69154)
![image](https://github.com/eve-autonomy/proj_launch/assets/33311630/e608db36-f4e6-4ad5-ad58-8358e03c595b)

2023-09-04 23:42 UTC, sfukuta commented
@yn-mrse レイアウトについて、これ以上の調整が難しいので、これでfixをお願いしたいです。

2023-11-29 06:12 UTC, sfukuta commented
@yn-mrse https://github.com/eve-autonomy/proj_launch/pull/15/commits/4fdff79e16deb98535755e52e05d98cb904c782f
moduleでまとめたnode graphにしたらスッキリしました。
ココからブロック単位で分割して、詳細なnode graphにします。

2025-01-16 05:54 UTC, closed without merging